services:
  - type: web
    name: avianguard-ai
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    plan: standard
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: MONGODB_URI
        sync: false
      - key: MONGODB_DB_NAME
        value: avian_guard
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: SMTP_EMAIL
        sync: false
      - key: SMTP_PASSWORD
        sync: false
      - key: RECEIVER_EMAILS
        sync: false
